import "./globals.css";

import { Box } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="flex justify-center bg-gray-300 h-full">
        <Box className="w-[480px] xl:w-[1280px] lg:w-[960px] md:w-[720px] sm:w-[540px] bg-gray-600">
          {children}
        </Box>
      </body>
    </html>
  );
}
