"use client";

import "./globals.css";
import "./i18n";

import { Box } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="flex justify-center bg-gray-300 h-full">
        <Box className="w-full md:w-full lg:w-[80%] bg-gray-600">
          {children}
        </Box>
      </body>
    </html>
  );
}
