"use client";

import "./globals.css";
import "./i18n";

import { Box } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="min-h-screen bg-gray-600">
      <body className="flex justify-center min-h-screen">
        <Box className="w-full p-6 bg-gray-200 md:w-full lg:w-[80%]">
          {children}
        </Box>
      </body>
    </html>
  );
}
